Feature/nwk create form
it-at-m/Praktikumsplaner pull request #214
Opened 2024-02-15 14:04 UTC by IamPekka058

**Description:**  

Implemented NwkCreateDialog.

**Reference:**

Issue: #16 

Notifying additional team members:

@mirrodi @MrSebastian @AnHo314

---
**Definition of Done (DoD):**

- [ ] Unittests gepflegt
- [ ] Dokumentation ist gepflegt

2024-02-16 07:16 UTC, IamPekka058 commented
Die package-lock.json habe ich nicht hochgeladen, da diese als Quelle das artifactory.muenchen.de verwendet. (Für OpenSource falsch)

2024-02-16 09:31 UTC, Tuckerle requested changes

2024-02-16 09:31 UTC, Tuckerle commented on praktikumsplaner-frontend/frontend/src/views/nachwuchskraefte/NachwuchskraefteView.vue
> +import router from "@/router";
unused import should be removed

2024-02-16 10:29 UTC, IamPekka058 commented on praktikumsplaner-frontend/frontend/src/types/NwkCreate.ts
> +}
[f1f229f](https://github.com/it-at-m/Praktikumsplaner/pull/214/commits/f1f229f6d337edf761bd8f0b7e4ab252d3a1e34b) Fixed this

2024-02-16 10:58 UTC, Tuckerle requested changes

2024-02-16 10:58 UTC, Tuckerle commented on praktikumsplaner-frontend/frontend/src/components/nachwuchskraefte/NwkCreateDialog.vue
> +                                    ></v-text-field>
Could/Should be extracted into separate component.

2024-02-16 10:58 UTC, Tuckerle commented on praktikumsplaner-frontend/frontend/src/components/nachwuchskraefte/NwkCreateDialog.vue
> +                                    ></v-text-field>
Could/Should be extracted into separate component.

2024-02-16 10:58 UTC, Tuckerle commented on praktikumsplaner-frontend/frontend/src/components/nachwuchskraefte/NwkCreateDialog.vue
> +                                    ></v-text-field>
Could/Should be extracted into separate component.

2024-02-16 12:02 UTC, LuisEinig commented on praktikumsplaner-frontend/frontend/src/components/nachwuchskraefte/NwkCreateDialog.vue
This is not documented in docs

2024-02-16 12:36 UTC, IamPekka058 commented on praktikumsplaner-frontend/frontend/src/components/nachwuchskraefte/NwkCreateDialog.vue
Did https://github.com/it-at-m/Praktikumsplaner/pull/214/commits/3b16c979f23c1cbf06bfb3da7ea314abd69ef1c8 fix that?

2024-02-16 13:55 UTC, IamPekka058 commented on praktikumsplaner-frontend/frontend/src/components/nachwuchskraefte/NwkCreateDialog.vue
> +                                </v-list-item>
Resolved by https://github.com/it-at-m/Praktikumsplaner/pull/214/commits/411ff015cffde28e3242fcf2677a0dd333358dfd ?

2024-02-16 14:29 UTC, Tuckerle requested changes

2024-02-16 14:29 UTC, Tuckerle commented on praktikumsplaner-frontend/frontend/src/components/common/JahrgangInput.vue
> +    nwk: NwkCreate;
This should be implemented in a way that it supports the v-model directive

2024-02-16 14:29 UTC, Tuckerle commented on praktikumsplaner-frontend/frontend/src/components/common/NameInput.vue
I think the v-if structure is not the best design. I would either split it up into two different components or use this component for both at the same time so it always shows Vorname and Nachname similar to StudienOrAusbildungsRichtungSelect. Another option would be to generalize the input so all the things that differ between vorname and nachname can be adjusted when creating.

2024-02-16 14:29 UTC, Tuckerle commented on praktikumsplaner-frontend/frontend/src/components/common/NameInput.vue
> +    nwk: NwkCreate;
This should be implemented in a way that it supports the v-model directive

2024-02-16 14:29 UTC, Tuckerle commented on praktikumsplaner-frontend/frontend/src/components/common/StudienrichtungOrAusbildungsrichtungSelect.vue
> +    nwk: NwkCreate;
This should be implemented in a way that it supports the v-model directive

2024-02-16 14:29 UTC, Tuckerle commented on praktikumsplaner-frontend/frontend/src/components/common/StudienrichtungOrAusbildungsrichtungSelect.vue
> +                        @click:clear="nwkProp.ausbildungsrichtung = undefined"
Even if its just one line of code, it should be put into a method so there is no/less logic in the template. Additionally if you need to do anything else when clearing for example showing a message or sending a request or trigger an event the code in the template would become hard to read and maintain.

2024-02-16 15:10 UTC, LuisEinig commented on doc/src/features/Nachwuchskraefte.md
> +There a two selectors to select either the training direction or course of study
```suggestion
There are two selectors to select either the training direction or course of study
```
typo

2024-02-16 15:16 UTC, LuisEinig commented
![grafik](https://github.com/it-at-m/Praktikumsplaner/assets/69314043/cad143d0-3357-4a60-9928-a992663e5f0c)
![grafik](https://github.com/it-at-m/Praktikumsplaner/assets/69314043/ff346a24-19ea-431e-8867-05be75a71c88)

When selecting both training and study the fields change position.
The dialog also has a scrollbar for minimal usage, this could be mitigated by making the dialog wider

2024-02-16 15:20 UTC, LuisEinig commented on praktikumsplaner-frontend/frontend/src/api/NwkService.ts
> +            })
There is no Feedback to the user if the creation was successful or not.

2024-02-19 09:57 UTC, MrSebastian requested changes

2024-02-20 07:44 UTC, Tuckerle commented on praktikumsplaner-frontend/frontend/src/views/nachwuchskraefte/NachwuchskraefteView.vue
> +});
That serves no purpose as the eventbus is global. So basically you are emitting the same event twice

2024-02-20 08:46 UTC, Tuckerle approved these changes

2024-02-20 09:27 UTC, LuisEinig commented on praktikumsplaner-frontend/frontend/src/components/nachwuchskraefte/ActiveNwkList.vue
> +});
is this still needed with the use of EventBus?

2024-02-20 09:30 UTC, LuisEinig commented on praktikumsplaner-frontend/frontend/src/components/nachwuchskraefte/NwkCreateDialog.vue
> +    });
the emit should be moved into a `then` bc if an error occurs the event should not be called

2024-02-20 09:33 UTC, LuisEinig commented on praktikumsplaner-frontend/frontend/src/components/nachwuchskraefte/VorlesungstageSelect.vue
> +});
style is not consistent with other components like e.g. NameInput

2024-02-20 09:47 UTC, LuisEinig commented on praktikumsplaner-frontend/frontend/src/views/nachwuchskraefte/NachwuchskraefteView.vue
> +            <active-nwk-list ref="nwkList"></active-nwk-list>
is this ref still needed?

2024-02-20 10:08 UTC, MrSebastian approved these changes

2024-02-20 12:01 UTC, LuisEinig approved these changes

2024-02-20 12:48 UTC, merged