🔀⬆️ migration to vue3
it-at-m/Praktikumsplaner pull request #218
Opened 2024-02-19 13:04 UTC by Tuckerle

**Description:**  

A short description about the request.

**Reference:**

Issue: #XXX

Notifying additional team members:

@mirrodi @MrSebastian @AnHo314

---
**Definition of Done (DoD):**

- [ ] Unittests gepflegt
- [ ] Dokumentation ist gepflegt

2024-02-21 12:59 UTC, LuisEinig commented on praktikumsplaner-frontend/apigateway/src/main/java/de/muenchen/oss/praktikumsplaner/configuration/GuiConfiguration.java
> +     * A index which returns the index.html as a resource.
```suggestion
     * A router which returns the index.html as a resource.
```
why was this changed?

2024-02-21 13:23 UTC, IamPekka058 requested changes

2024-02-21 13:23 UTC, IamPekka058 commented on praktikumsplaner-frontend/frontend/index.html
> +                >Damit der RefArch-Kickstarter korrekt funktioniert, muss
Praktikumsplaner instead of RefArch-Kickstarter?

2024-02-21 13:23 UTC, IamPekka058 commented on praktikumsplaner-frontend/frontend/src/api/NwkService.ts
> +                    });
I would move defaultResponseHandler into else

2024-02-21 13:23 UTC, IamPekka058 commented on praktikumsplaner-frontend/frontend/src/api/NwkService.ts
>                  });
I would move defaultResponseHandler into else

2024-02-21 14:36 UTC, LuisEinig commented
Input names in Nwk update dialog are cut off

2024-02-22 11:24 UTC, danielnwz requested changes

2024-02-22 13:23 UTC, LuisEinig commented on praktikumsplaner-frontend/frontend/src/types/Praktikumsstelle.ts
> -        public dringlichkeit: string,
This was changed bc a partially empty Praktikumsstelle was created in Meldung and this lead to Dringlichkeit being the only field which label was on top even when nothing was typed bc a value had to be set beforehand

2024-02-22 14:06 UTC, LuisEinig commented on praktikumsplaner-frontend/frontend/src/types/Studiengang.ts
> +        color: "deep-purple-lighten-4",
can you do that?

2024-02-22 14:32 UTC, danielnwz approved these changes

2024-02-22 15:07 UTC, IamPekka058 approved these changes

2024-02-22 15:11 UTC, merged