📝 added Definition of Done to standard issue template
it-at-m/Praktikumsplaner pull request #53
Opened 2023-10-06 08:45 UTC by LuisEinig

**Description**

**Reference**

Issues #44

2023-10-06 17:15 UTC, MrSebastian commented on .github/ISSUE_TEMPLATE/user_story.md
> +- [ ] Dokumentation ist gepflegt
according to the issue, these two tasks should be part of the pull request template:

```
Punkte für Pull Request:

    Unittest gepflegt
    Dokumentation ist gepflegt
```

2023-10-10 06:29 UTC, MrSebastian commented on .github/ISSUE_TEMPLATE/pull_request_template.md
> +- [ ] Unittest gepflegt
```suggestion
- [ ] Unittests gepflegt
```

2023-10-10 09:40 UTC, MrSebastian approved these changes

2023-10-11 13:01 UTC, MrSebastian commented
we should update the pull request title to have a better match to changes. In the request pr-template and issue-template is getting changed.

2023-10-11 13:06 UTC, MrSebastian requested changes
the change from @mirrodi should be addressed

2023-10-12 12:02 UTC, LuisEinig commented
> In order to monitor and mentor the work I would like that all the mentors are assigned as reviewers, although their approval is not needed. This should be set in the PR template

it is only possible to assign someone to the PR from the template, not to assign them as reviewers. Github does not support that functionality sadly. Maybe this can be done in the Project Settings, but I am not able to change them

2023-10-12 12:05 UTC, Tuckerle approved these changes

2023-10-12 12:06 UTC, MrSebastian approved these changes

2023-10-12 12:07 UTC, merged